title: Seething Construct Studio
description: An indie studio creating dark, gritty, and arcane 2D top-down games.
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have onekk
baseurl: ""
url: "https://scstudio.dev"
author:
  name: Seething Construct Studio
  email: noreply@scstudio.dev
  url: https://scstudio.dev
