title: Seething Construct Studio
description: An indie studio creating dark, gritty, and arcane 2D top-down games.
theme: jekyll-theme-tactile
baseurl: ""
url: "https://scstudio.dev"
author:
  name: Seething Construct Studio
  email: noreply@scstudio.dev
  url: https://scstudio.dev
